version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: movie_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pelicula
      MYSQL_USER: userDasc
      MYSQL_PASSWORD: Dani2025*.
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - movie_network

networks:
  movie_network:
    driver: bridge

volumes:
  mysql_data: 